import { readFileSync, writeFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import type { DashboardPost } from '../../../../api/types.ts';
import type { CustomChartConfig, CustomDimension, SocialDashboardWidget } from '../types-social-dashboard.ts';
import { aggregateCustom, aggregateTable, aggregateHeatmap } from '../dashboard-aggregations.ts';
import { aggregateObjectList, aggregateObjectTable } from '../object-list-aggregations.ts';
import type { ReportScope } from '../types-social-dashboard.ts';
import { objectFieldOf, objectFieldOfTable } from '../types-social-dashboard.ts';
import { applyWidgetFilters, applyWidgetValueFilters, tablePrimaryDimension } from '../SocialWidgetRenderer.tsx';
import { INITIAL_FILTERS, intersectWithScope, applyFilters } from '../use-dashboard-filters.ts';

/**
 * Cross-language parity recorder + guard for the server-side aggregation engine (P2).
 *
 * `aggregateCustom` IS the spec. This test runs it over the shared fixtures
 * (parity_input.json) and records its output as the golden file
 * (parity_fixtures.json), which the Python engine must reproduce byte-for-byte
 * (api/tests/test_dashboard_aggregate_parity.py).
 *
 * Two modes:
 *   - `UPDATE_PARITY=1 npm test` → regenerate the golden from the real TS spec.
 *   - default → assert the current TS output still matches the committed golden
 *     (so this doubles as a TS-side regression test guarding the spec from drift).
 */

const inputUrl = new URL('./parity_input.json', import.meta.url);
const goldenUrl = new URL('./parity_fixtures.json', import.meta.url);

interface ParityCase {
  name: string;
  config: Partial<CustomChartConfig> & { metric: CustomChartConfig['metric'] };
}
interface WidgetCase {
  name: string;
  widget: Pick<SocialDashboardWidget, 'filters'> & { customConfig: CustomChartConfig };
}
interface TableCase {
  name: string;
  widget: Pick<SocialDashboardWidget, 'filters'> & { tableConfig: NonNullable<SocialDashboardWidget['tableConfig']> };
}
interface ScopeCase {
  name: string;
  scope: ReportScope;
}
interface ParityInput {
  _doc?: string;
  posts: DashboardPost[];
  cases: ParityCase[];
  widget_cases?: WidgetCase[];
  table_cases?: TableCase[];
  object_cases?: WidgetCase[];
  object_table_cases?: TableCase[];
  heatmap_cases?: WidgetCase[];
  post_table_feed_cases?: TableCase[];
  scope_cases?: ScopeCase[];
}

function loadInput(): ParityInput {
  return JSON.parse(readFileSync(inputUrl, 'utf-8')) as ParityInput;
}

function record(input: ParityInput) {
  const posts = input.posts;
  return {
    _doc:
      'GENERATED by parity.record.test.ts from parity_input.json via the real ' +
      'aggregateCustom + applyWidgetFilters/applyWidgetValueFilters. Do not hand-edit; ' +
      'run `UPDATE_PARITY=1 npm test` to regenerate. The Python engine ' +
      '(api/services/dashboard_aggregate.py + dashboard_widget_filters.py) must reproduce ' +
      'every `expected` exactly — see api/tests/test_dashboard_aggregate.py.',
    posts,
    cases: input.cases.map((c) => ({
      name: c.name,
      config: c.config,
      // basePosts === posts mirrors the share path (no dashboard-level filter):
      // the percent denominator is the full displayed set.
      expected: aggregateCustom(posts, c.config as CustomChartConfig, [], posts),
    })),
    // Full per-widget pipeline: row filter → value filter → aggregate, exactly as
    // CustomWidget runs it (basePosts = the unfiltered set).
    widget_cases: (input.widget_cases ?? []).map((wc) => {
      const cfg = wc.widget.customConfig;
      const rowFiltered = applyWidgetFilters(posts, wc.widget.filters);
      const aggPosts = applyWidgetValueFilters(
        rowFiltered, wc.widget.filters, cfg.dimension as CustomDimension | undefined,
      );
      return {
        name: wc.name,
        widget: wc.widget,
        expected: aggregateCustom(aggPosts, cfg, [], posts),
      };
    }),
    // Group-table pipeline: row filter → value filter (primaryDim = first
    // dimension column) → aggregateTable.
    table_cases: (input.table_cases ?? []).map((tc) => {
      const cfg = tc.widget.tableConfig;
      const rowFiltered = applyWidgetFilters(posts, tc.widget.filters);
      const aggPosts = applyWidgetValueFilters(rowFiltered, tc.widget.filters, tablePrimaryDimension(cfg));
      return {
        name: tc.name,
        widget: tc.widget,
        expected: aggregateTable(aggPosts, cfg),
      };
    }),
    // Object-list (element-as-unit) chart pipeline.
    object_cases: (input.object_cases ?? []).map((oc) => {
      const cfg = oc.widget.customConfig;
      const rowFiltered = applyWidgetFilters(posts, oc.widget.filters);
      const aggPosts = applyWidgetValueFilters(rowFiltered, oc.widget.filters, cfg.dimension as CustomDimension | undefined);
      const field = objectFieldOf(cfg)!;
      return { name: oc.name, widget: oc.widget, expected: aggregateObjectList(aggPosts, field, cfg) };
    }),
    // Object-list table pipeline.
    object_table_cases: (input.object_table_cases ?? []).map((tc) => {
      const cfg = tc.widget.tableConfig;
      const rowFiltered = applyWidgetFilters(posts, tc.widget.filters);
      const aggPosts = applyWidgetValueFilters(rowFiltered, tc.widget.filters, tablePrimaryDimension(cfg));
      const field = objectFieldOfTable(cfg)!;
      return { name: tc.name, widget: tc.widget, expected: aggregateObjectTable(aggPosts, field, cfg) };
    }),
    // Heatmap (2D categorical pivot): same per-widget pipeline, aggregateHeatmap.
    heatmap_cases: (input.heatmap_cases ?? []).map((hc) => {
      const cfg = hc.widget.customConfig;
      const rowFiltered = applyWidgetFilters(posts, hc.widget.filters);
      const aggPosts = applyWidgetValueFilters(
        rowFiltered, hc.widget.filters, cfg.dimension as CustomDimension | undefined,
      );
      return { name: hc.name, widget: hc.widget, expected: aggregateHeatmap(aggPosts, cfg) };
    }),
    // Post-mode table feed: aggregateTable (post mode → aggregateTablePostMode)
    // over row-filtered posts; record the ordered __key (post_id) selection.
    post_table_feed_cases: (input.post_table_feed_cases ?? []).map((tc) => {
      const cfg = tc.widget.tableConfig;
      const rowFiltered = applyWidgetFilters(posts, tc.widget.filters);
      return { name: tc.name, widget: tc.widget, expected: aggregateTable(rowFiltered, cfg).map((r) => r.__key) };
    }),
    // reportScope narrowing: the read-only share promotes the scope to active
    // filters over an empty viewer selection. Record the kept post_ids so the
    // Python `apply_report_scope` must reproduce the same set.
    scope_cases: (input.scope_cases ?? []).map((sc) => ({
      name: sc.name,
      scope: sc.scope,
      expected: applyFilters(posts, intersectWithScope(INITIAL_FILTERS, sc.scope)).map((p) => p.post_id),
    })),
  };
}

describe('server-aggregation parity golden', () => {
  it('TS output matches the committed golden (run UPDATE_PARITY=1 to regenerate)', () => {
    const fixtures = record(loadInput());

    if (process.env.UPDATE_PARITY) {
      writeFileSync(goldenUrl, `${JSON.stringify(fixtures, null, 2)}\n`, 'utf-8');
      return;
    }

    const golden = JSON.parse(readFileSync(goldenUrl, 'utf-8')) as ReturnType<typeof record>;
    const goldenByName = new Map(golden.cases.map((c) => [c.name, c.expected]));
    const goldenWidgetByName = new Map((golden.widget_cases ?? []).map((c) => [c.name, c.expected]));

    expect(fixtures.cases.map((c) => c.name).sort()).toEqual(
      golden.cases.map((c) => c.name).sort(),
    );
    for (const c of fixtures.cases) {
      expect(c.expected, `case ${c.name}`).toEqual(goldenByName.get(c.name));
    }
    expect(fixtures.widget_cases.map((c) => c.name).sort()).toEqual(
      (golden.widget_cases ?? []).map((c) => c.name).sort(),
    );
    for (const c of fixtures.widget_cases) {
      expect(c.expected, `widget case ${c.name}`).toEqual(goldenWidgetByName.get(c.name));
    }

    const goldenTableByName = new Map((golden.table_cases ?? []).map((c) => [c.name, c.expected]));
    expect(fixtures.table_cases.map((c) => c.name).sort()).toEqual(
      (golden.table_cases ?? []).map((c) => c.name).sort(),
    );
    for (const c of fixtures.table_cases) {
      expect(c.expected, `table case ${c.name}`).toEqual(goldenTableByName.get(c.name));
    }

    const gObj = new Map((golden.object_cases ?? []).map((c) => [c.name, c.expected]));
    for (const c of fixtures.object_cases) {
      expect(c.expected, `object case ${c.name}`).toEqual(gObj.get(c.name));
    }
    const gObjTbl = new Map((golden.object_table_cases ?? []).map((c) => [c.name, c.expected]));
    for (const c of fixtures.object_table_cases) {
      expect(c.expected, `object table case ${c.name}`).toEqual(gObjTbl.get(c.name));
    }

    const gHeat = new Map((golden.heatmap_cases ?? []).map((c) => [c.name, c.expected]));
    expect(fixtures.heatmap_cases.map((c) => c.name).sort()).toEqual(
      (golden.heatmap_cases ?? []).map((c) => c.name).sort(),
    );
    for (const c of fixtures.heatmap_cases) {
      expect(c.expected, `heatmap case ${c.name}`).toEqual(gHeat.get(c.name));
    }

    const gPostFeed = new Map((golden.post_table_feed_cases ?? []).map((c) => [c.name, c.expected]));
    expect(fixtures.post_table_feed_cases.map((c) => c.name).sort()).toEqual(
      (golden.post_table_feed_cases ?? []).map((c) => c.name).sort(),
    );
    for (const c of fixtures.post_table_feed_cases) {
      expect(c.expected, `post-table feed case ${c.name}`).toEqual(gPostFeed.get(c.name));
    }

    const gScope = new Map((golden.scope_cases ?? []).map((c) => [c.name, c.expected]));
    expect(fixtures.scope_cases.map((c) => c.name).sort()).toEqual(
      (golden.scope_cases ?? []).map((c) => c.name).sort(),
    );
    for (const c of fixtures.scope_cases) {
      expect(c.expected, `scope case ${c.name}`).toEqual(gScope.get(c.name));
    }
  });
});
