import { useState, useMemo } from 'react';
import { FileText, LayoutGrid, List, Search, Sparkles, X } from 'lucide-react';
import type { Agent } from '../../../../api/endpoints/agents.ts';
import type { ArtifactListItem } from '../../../../api/endpoints/artifacts.ts';
import { ArtifactLibraryCard } from '../../../artifacts/ArtifactLibraryCard.tsx';
import { Input } from '../../../../components/ui/input.tsx';
import { StatusBadge } from '../agent-status-utils.tsx';
import { cn } from '../../../../lib/utils.ts';

interface TaskArtifactsTabProps {
  task: Agent;
  artifacts: ArtifactListItem[];
}

export function AgentArtifactsTab({ task, artifacts }: TaskArtifactsTabProps) {
  const [search, setSearch] = useState('');
  const [viewMode, setViewMode] = useState<'grid' | 'list'>('grid');

  const filtered = useMemo(() => {
    let list = artifacts ?? [];
    if (search.trim()) {
      const q = search.toLowerCase();
      list = list.filter((a) => a.title.toLowerCase().includes(q));
    }
    list.sort((a, b) => b.created_at.localeCompare(a.created_at));
    return list;
  }, [artifacts, search]);

  if (artifacts.length === 0) {
    return (
      <div className="flex flex-1 flex-col overflow-hidden">
        <div className="flex h-11 shrink-0 items-center gap-3 px-6">
          <h1 className="truncate font-heading text-sm font-semibold tracking-tight text-foreground">{task.title}</h1>
          <StatusBadge status={task.status} />
        </div>
        <div className="flex flex-1 items-center justify-center p-8">
          <div className="flex flex-col items-center gap-4 max-w-xs text-center">
            <div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-gradient-to-br from-violet-500/20 to-violet-500/5 border border-violet-500/10">
              <Sparkles className="h-7 w-7 text-violet-500/50" />
            </div>
            <div>
              <p className="font-heading text-sm font-semibold tracking-tight text-foreground">No artifacts yet</p>
              <p className="mt-1 text-xs text-muted-foreground leading-relaxed">
                Charts, reports, and data exports generated by this agent will appear here.
              </p>
            </div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="flex flex-1 flex-col min-h-0 overflow-hidden bg-background">
      {/* Header — inline with controls */}
      <div className="flex h-11 shrink-0 items-center gap-3 px-6">
        <h1 className="truncate font-heading text-sm font-semibold tracking-tight text-foreground">{task.title}</h1>
        <StatusBadge status={task.status} />
        <span className="text-[11px] text-muted-foreground">
          {filtered.length} artifact{filtered.length !== 1 ? 's' : ''}
        </span>
        <div className="flex-1" />
        {/* Search */}
        <div className="relative w-48">
          <Search className="absolute left-2.5 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-muted-foreground" />
          <Input
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Search..."
            className="h-7 pl-8 text-xs"
          />
          {search && (
            <button onClick={() => setSearch('')} className="absolute right-2 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground">
              <X className="h-3 w-3" />
            </button>
          )}
        </div>
        {/* View toggle */}
        <div className="flex items-center rounded-md border border-border overflow-hidden">
          <button
            onClick={() => setViewMode('grid')}
            className={cn('flex h-7 w-7 items-center justify-center transition-colors', viewMode === 'grid' ? 'bg-accent text-foreground' : 'text-muted-foreground hover:text-foreground')}
          >
            <LayoutGrid className="h-3.5 w-3.5" />
          </button>
          <button
            onClick={() => setViewMode('list')}
            className={cn('flex h-7 w-7 items-center justify-center border-l border-border transition-colors', viewMode === 'list' ? 'bg-accent text-foreground' : 'text-muted-foreground hover:text-foreground')}
          >
            <List className="h-3.5 w-3.5" />
          </button>
        </div>
      </div>

      {/* Content */}
      <div className="flex-1 overflow-y-auto px-6 pb-6">
        {filtered.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-16 text-center">
            <FileText className="h-8 w-8 opacity-15 mb-3" />
            <p className="text-sm text-muted-foreground">No artifacts match your search</p>
          </div>
        ) : viewMode === 'grid' ? (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
            {filtered.map((artifact) => (
              <ArtifactLibraryCard key={artifact.artifact_id} artifact={artifact} view="grid" />
            ))}
          </div>
        ) : (
          <div className="flex flex-col gap-1.5">
            {filtered.map((artifact) => (
              <ArtifactLibraryCard key={artifact.artifact_id} artifact={artifact} view="list" />
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
